test: &default

  # Credentials for REST APIs
  client_id: AZ6QyBCEMUjlJxggcgtVBmKNHdyqKTtey9pwo9ANkqxSiPiptuhSVM_DBXnO
  client_secret: ECAc4BDqp8M7QLwL-LZFtbod5cXQpxUBBeq5fRnBY9mc8becqiCi4fVCruWy

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-1RS81362V9766120D
  username: adam.robbie-facilitator_api1.gmail.com
  password: 1392049957
  signature: AolubZXrkCc.G0pObQvoNEIufiqYAZRUInVeji8ItXT52NwtpWZKbgvc
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: adam.robbie@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
